chore(main): check discount from param before unset sale price
ecomplus/products-feed pull request #19
Opened 2024-06-19 03:04 UTC by matheusgnreis

2024-06-19 19:26 UTC, leomp12 reviewed
Mas por que?
Isso não faz muito sentido não, e pode influenciar erroneamente em várias lojas, tá ciente?
Quer dizer, não é porque o lojista gerou o feed com 10% de desconto que ele quer usar um preço que ele configurou pra Black Friday em janeiro por exemplo.

2024-06-19 19:27 UTC, leomp12 commented
Me parece uma gambiarra errada pra atender um caso específico, com efeitos colaterais.
Explica pelo menos o caso de uso...

2024-06-20 04:16 UTC, matheusgnreis commented
Realmente e peguei uma consultoria com google aqui e me falaram que quando tem o desconto pelo XML, deve haver apenas a tag price no xml, mesmo que o produto esteja em promoção:

"Pois é, Matheus.. Entendemos também que o melhor dos casos seríamos estar enviando um único preço em todos os pontos, XML, site e dados estruturados sendo o menor da página, de forma que não precisássemos enviar o atributo [sale_price], apenas o [price] em que fazendo desta maneira, temos a possibilidade de trabalhar descontos com menos burocracias  e processos mais automatizados, recomendado também em nossas consultorias recebidas na conta."

Isso porque a Tia Sônia quer fazer esse "ajuste" no XML e ai pra evitar travar a conta deles no merchant, estou tentando fazer o mesmo passo e acompanhamento que ocorreu com a disfoil.

A alteração anterior também não resolve, porque daria o erro que citou e continuaria tendo um sale_price, que nesse caso não se trata de um preço promocional e sim um preço unico de desconto na modalidade a vista.

2024-06-20 04:24 UTC, leomp12 commented
Na verdade o primeiro commit não tem nada a ver com o que você comentou agora kkk

2024-06-20 04:28 UTC, leomp12 commented
No fim das contas o que você quer é só remover o `sale_price` quando houver desconto forçado no XML?

2024-06-20 04:40 UTC, leomp12 requested changes

2024-06-20 04:40 UTC, leomp12 commented on lib/main.php
> +          $entry['sale_price'] = $body['price'] . ' ' . @$body['currency_id'];
Editar isso aqui só complica...

2024-06-20 04:40 UTC, leomp12 commented on lib/main.php
> +          }
```suggestion
          if ($discount > 0 && isset($entry['sale_price'])) {
            $entry['price'] = $entry['sale_price'];
            unset($entry['sale_price']);
            unset($entry['sale_price_effective_date']);
          }
```

2024-06-20 04:40 UTC, leomp12 commented on lib/main.php
> +          }
Se a intenção é só não ter o `sale_price` quando houver desconto via parâmetro de URL, o mais simples é só adicionar esse trecho aí movendo pro `price`, não precisa mexer nada no restante da lógica..

2024-06-20 04:40 UTC, leomp12 commented on lib/main.php
> +          }
E aliás ; não é opcional em PHP

2024-06-20 16:57 UTC, closed without merging