Insert picture type normal
ecomplus/products-feed pull request #6
Opened 2020-11-13 14:35 UTC by matheusgnreis

When products became from Bling, images are only normal, so they do not go to XML, so i just added this option too

2020-11-13 15:26 UTC, leomp12 requested changes
Uai @matheusgnreis , mas na verdade tem um fallback lá em qualquer size se não houver `zoom` nem `big`:

```php
         else {
            foreach ($img as $size => $img_obj) {
              // get any image size excepting small
              if ($size !== 'small') {
                $img_link = @$img_obj['url'];
                break;
              }
            }
          }
```

Nesse caso ele pegaria o `normal` ou `custom`, só não pegaria `small`...
Isso não aconteceu com algum produto? Tem certeza que não é cache ou algo do tipo?

2020-11-14 00:43 UTC, matheusgnreis commented
https://storefront.e-com.plus/products-feed.xml?store_id=1058&domain=www.bluekids.com.br
Pesquisando por Roupa Social Infantil Menino Camisa Polo retorna um XML sem nenhum link de imagem, mas as tags de imagem lá

2020-11-17 05:22 UTC, matheusgnreis commented
@leomp12

2020-11-17 19:04 UTC, leomp12 commented
Hm, mas aí o erro está no `foreach`, ele deveria ser uma solução de fallback para qualquer caso fora do ideal (sem zoom e big). Adicionar um outro `else if` ali é uma como mascarar o erro, o problema mesmo é que ele está batendo o `_id` dentro do objeto, o correto seria:

```php
          else {
            foreach ($img as $size => $img_obj) {
              // get any image size excepting small
              if (is_array($img_obj) && isset($img_obj['url']) && $size !== 'small') {
                $img_link = @$img_obj['url'];
                break;
              }
            }
          }

2020-11-17 19:04 UTC, closed without merging

2020-11-17 19:09 UTC, leomp12 commented
@matheusgnreis comitei o fix e já está corrigido o XML do exemplo.